data:
  path: "/home/jamesdi1993/datasets/2dlaser/freiburg/sequences"
  mode: "max" # number of steps to run sequence. One of [min, max, custom]
  steps: -1   # note: need mode to be 'custom' to take effect. Run the first n steps.
map:
  grid_min: [ -50, -50 ]
  grid_max: [ 50, 50 ]
  origin: [0, 0, 0]
  grid_size: 0.2
agent:
  enable_communicate: true
  n_agents: 5
  weight: [[0.75, 0.25, 0, 0, 0],
           [0.25, 0.5, 0.25, 0, 0],
           [0, 0.25, 0.5, 0.25, 0],
           [0, 0, 0.25, 0.5, 0.25],
           [0, 0, 0, 0.25, 0.75]]
  dist_thresh: 10
  central_robot_index: -1
process:
  sigma: 0.1
  mu_prior: 0.5
  c: 1.0
  l: 0.1
  max_leaf_size: 200
  tsdf_thresh: 0.5
  outlier_thresh: [0.01, 5.0]
  window_update: 1
  window_evaluate: 5
  count_thresh: 0
visualization:
  plot_agent_indices: [0,1,2,3,4]
  window_plot: -1
evaluation:
  grid_size_eval: 0.5
  window_evaluate: 5
  write_prediction: true
  output_dir: "/home/jamesdi1993/workspace/Distributed-Sparse-GP/results/freiburg"

