data:
  dates: ["2012-01-08", "2012-04-29", "2012-06-15"]
  path: "/home/jamesdi1993/datasets/NCLT"
  mode: "custom"
  seq: 6
  steps: 500 # note: need mode to be 'custom' to take effect. Run the first n steps.
map:
  grid_min: [ -400, -150 ]
  grid_max: [ 150, 750 ]
  origin: [0, 0, 0]
  grid_size: 0.25
agent:
  enable_communicate: true
  n_agents: 3
  dist_thresh: 200
  central_robot_index: -1
process:
  sigma: 0.1
  mu_prior: 5.0
  c: 1.0
  l: 0.2
  max_leaf_size: 50
  tsdf_thresh: 5.0
  outlier_thresh: [1.0, 30.0]
  window_update: 1
  down_sampling: 0.5
  count_thresh: 0
visualization:
  plot_agent_indices: [0, 1, 2]
  window_plot: -1
evaluation:
  grid_size_eval: 1.0
  window_evaluate: 100
  write_prediction: true
  output_dir: "/home/jamesdi1993/workspace/Distributed-Sparse-GP/results/nclt/test"
